include/tins/config.h, include/tins/config.h.in
In an internal project we include libtins as a git submodule in a larger project and build it using our own build system. We want to build libtins without WPA2 decryption support but would like not to change a source file in libtins (i.e. the included `config.h`). Since this is currently not possible I added an include guard to `config.h`. This enables us to define `TINS_CONFIG_H` in our build so the default `config.h` does not get used.
Another solution would be to remove the `config.h` from the repository, include it using `#include <config.h>` in the other source files (as [recommended](https://www.gnu.org/software/autoconf/manual/autoconf.html#Configuration-Headers) by autoconf) and generate it inside the build dir using CMake. I think this would be the cleaner solution but since it …
=> add an include guard to config.h

include/tins/dot11/dot11_mgmt.h, tests/include/tests/dot11_mgmt.h, tests/src/dot11/beacon.cpp
According to the IEEE802.11 2012 Standard (8.4.1.4 Capability Information field) the flag named reserved is now called "Radio Measurement".
=> Fixed field name corresponding to IEEE 802.11-2012

include/tins/cxxstd.h
This is how I fixed mfontanini/libtins#64, enabling compilation on VS2013 when configuring with LIBTINS_ENABLE_CXX11=0 defined. Still seems like a good idea to check this macro here, even with mfontanini/libtins@3478c7b09a746b5e3fbcbbf2e84e606a7291e2a5.
=> Ensure HAVE_CXX11 is checked when defining TINS_IS_CXX11

include/tins/dot11/dot11_mgmt.h, src/dot11/dot11_mgmt.cpp
Made rsn_information() a const member function in order to make Dot11ManagementFrame immutable. 
Otherwise a non const rsn_information() called like this:
Tins::RSNInformation rsn_info = tins_mgmt_frame->rsn_information();
will result in following compiler error:
candidate function not viable: no known conversion from 'const Tins::Dot11AssocRequest' to
'Tins::Dot11ManagementFrame' for object argument RSNInformation rsn_information();
=> Made rsn_information() a const member function 

include/tins/dot11/dot11_mgmt.h
I noticed that channels_type has two different meanings.
It is used in combination with the supported_channels() method and it is part of the ibss_dfs_params struct used in combination with the ibss_dfs() method. Since channels_type has a rather general definition it will work without any problems.
/**
* The supported channels container type.
*/
typedef std::vector<std::pair<uint8_t, uint8_t> > channels_type;
But without looking into the IEEE 802.11 standard I got quite confused by this dual use.
Actually the difference is pretty significant.
In section 8.4.2.20 "Supported Channels element" of IEEE 802.11-2012 channels_type would have the following content:
channels_type.first == "First Channel Number" field -> integer
channels_type.second == "Number of Channels" field -> integer
Within …
=> Added channel_map_type

src/ip.cpp
Currently, the IP protocol field for non-fragmented packets is forcibly overwritten to the protocol of the inner PDU even if that PDU is a RawPDU. I believe this behavior contradicts the documentation.
> If this packet has been crafted manually and the inner_pdu is, for example, a RawPDU, then setting the protocol yourself is necessary.
I discovered this when trying to serialize an IP PDU with an inner RawPDU. Despite explicitly setting the protocol of the IP PDU before serialization, it always serialized as `0xff`.
=> Perserve IP protocol when using RawPDU

src/network_interface.cpp
I was trying to run interfaces_info.cpp from examples and I got runtime_error exception. This was happening because ifa_addr (struct ifaddrs) is NULL and hence found_hw is set to false. This is valid case and hence I'm removing the exception.
=> Incase of tunnel interface(VPN) mac address can be 0

include/tins/sniffer.h, src/sniffer.cpp
I have added to the sniffer the the capability of setting the capturing direction with pcap - pcap_setdirection. Now, if you can decide whether you capture all traffic or only incoming or outgoing. This can be particularly interesting for those who only need to capture packets in a single direction, as it was in my case - incoming packets only -  and could not rely on any filter of IP or MAC addresses because of my particular use case. Please, merge if if you find it interesting.
=> Added pcap_setdirection to sniffer

include/tins/address_range.h, include/tins/internals.h, src/internals.cpp
Hi,
i was a bit confuse about the result of `AddressRange::from_mask` , because of the comment 
> Creates an address range from a base address
i thought that method return the complete network address range of the ip and subnet mask e.g: 
- 192.168.1.128/255.255.255.0 ⇒ 192.168.1.1 ... 192.168.1.254 
but the method return only the range from the base ip to end of the network (depends of subnetmask)
- 192.168.1.128/255.255.255.0 ⇒ 192.168.1.128 ... 192.168.1.254
So i added ` Internals::first_address_from_mask `- methods and add a call in `AddressRange::from_mask`  instead of pass the base ip. So method returns the range  from the first to the last ip depends of a address in the network and the subnet mask.
best regards
stubbfel
=> calc the complete addressrange of a network when call AddressRange::from_mask

src/eapol.cpp
right now it is being set unconditionally and without reason, regardless of whether it was explicitly changed earlier in the code
=> don't set key_t to 0 when setting a key, because the two fields are unrelated

CMakeLists.txt
This fix give ability to build libtins as sub-project.
I.e.
```
add_subdirectory("${NMDREADER_SOURCE_DIR}/external/libtins")  
```
=> Fix CMakeLists.txt for build as part of other project

src/dns.cpp, src/llc.cpp
- The scope of the variable 'last_index' & 'index' could be reduced.
- Prefer prefix ++/-- operators for non-primitive types.
=> Fix Cppcheck 1.75 warnings

src/tcp_ip/stream.cpp
Since pull request #149 has stalled, and I've just stubbed my toe on exactly the same bug, I hope this pull request is more suitable for merging.
=> Correct typo preventing user buffer management for server TCP streams.

include/tins/tcp_ip/stream.h
An application using the (new) TCPIP stream_follower will most likely want to track some additional information per stream. This could be done in external data structures, using some kind of stream identifier. On the other hand, there is already a nice life-cycle for streams as created by libTins.
With this addition, a user can hook into new_stream_callback, to attach and initialize his own data to the stream. On subsequent callbacks, he can retrieve this data and change it via the reference. Finally, using stream_closed_callback and stream_termination_callback, he can access it one last time.
As a simple example consider following an HTTP stream, where you might want to save the last request in the stream, so you know what the current response is answering to.
=> Feature - Adding user data to TCP Streams

src/tcp_ip/flow.cpp, src/tcp_ip/stream.cpp, src/tcp_ip/stream_follower.cpp, tests/src/tcp_ip.cpp
I would like to offer/discuss these changes to TCPIP::Stream/StreamFollower/Flow:
(a) Flow sequence numbers during/after SYN/ACK.
Currently, the sequence number from the observed SYN packet is taken to initialize the data_tracker of the respective flow. The sequence number is then incremented by 1 once the flow itself sends an ACK (since the flow will not see the ACK to its own SYN). I think this is odd and means after the initial exchange of SYN, SYN/ACK, ACK, the client flow sequence number is correct, but the server flow sequence number is still off by one.
My proposed change is to handle flow sequence numbers during SYN/ACK the same way they are handled during payload processing: They are incremented directly on observing packets that contained the data. For SYN packets that means the …
=> Changes to stream/flow initialization (stream attachment and sequence numbers)

include/tins/tcp_ip/data_tracker.h, include/tins/tcp_ip/flow.h, src/tcp_ip/data_tracker.cpp, src/tcp_ip/flow.cpp
I was recently using the (new?) stream follower code for TCP streams and had issues with following TCP streams of captures with packet loss. The application layer (HTTP) allowed me to "recover" from gaps in a flow, by realizing that HTTP requests and responses in a stream cannot be reordered, since a subsequent request/response will only be sent after the previous one has been completely received by the server/client, who answers with a response/request.
If packets are lost (not in the original TCP stream, but just while capturing that stream), flows will get stuck and start buffering indefinitely. By registering an out-of-order callback, the application layer can notice that gap and if it detects the start of a new response/request in an out-of-order chunk, can skip ahead in the flow, of …
=> Feature - Skipping ahead in TCP flows.

CMakeLists.txt
This is to have control over the building of the examples and tests from e.g. parent CMake projects or from the command-line.
I left the default to still be building tests and examples by default.
=> Add CMakeLists options LIBTINS_BUILD_EXAMPLES and LIBTINS_BUILD_TESTS

include/tins/rsn_information.h
This change adds all current Cipher and AKM suites as defined by the 802.11-2016 standard.
Additionally, this changes the name of AKMSuites::PMKSA to AKMSuites::EAP to accurately reflect the AKM type as PMKSA can be utilized in EAP_SHA256_FIPSB/EAP_SHA384_FIPSB.
=> added cipher and akm suites from 802.11-2016

include/tins/dot11/dot11_base.h, src/dot11/dot11_base.cpp, tests/include/tests/dot11.h, tests/include/tests/dot11_mgmt.h, tests/src/dot11/ack_test.cpp, tests/src/dot11/dot11_test.cpp
Added getter, setter, and tests for the more data field of the 802.11 header.
=> Exposing More Data Field in 802.11 Header

CMakeLists.txt
Hi Matias,
When running `make install` on both Linux and macOS systems, the headers were being installed as `/usr/local/*.h` rather than the expected `/usr/local/include/tins/.*`.
Small PR to adjust the install location so that all headers and structure are copied as expected.
Best wishes,
Alex
=> Fix header install location.

src/icmpv6.cpp
I was trying to implement IPv6 next hop determination since some functions in my application require that I deliver packets with Ethernet frames attached to PacketSender and I needed next-hop link-layer info for the construction. I noticed that send_recv() does not correctly match ICMPv6 ND protocol responses since the checks are not implemented. I added the check of the flags and check if code equals zero according to https://tools.ietf.org/html/rfc4861#page-39 to ICMPv6 response matching.
=> Implemented matching for ND protocol related ICMPv6 messages

include/tins/tcp.h
When reading TCP packets with esoteric (or corrupt) values for option types, the ubsan fsanitize=enum will trigger if the read value is not in range of the enum. The range of an enum without fixed underlying type is determined by the highest bit set in any of its enumerators, so if `TCP::OptionTypes` has highest enumerator `ALTCHK  = 14` it cannot take values above 15.
Define enumerators [per IANA](https://www.iana.org/assignments/tcp-parameters/tcp-parameters.xhtml#tcp-parameters-1) with bit 7 set to ensure that `TCP::OptionTypes` can take any 8-bit value.
An alternative (C++11 only) would be to give `TCP::OptionTypes` underlying type `uint8_t`.
=> Ensure TCP::OptionTypes has 8-bit range

CMakeLists.txt, src/CMakeLists.txt
Hi Matias,
I saw you'd raised #263 - hadn't realised that was a requirement or the intended behaviour.
This PR uses the HEADERS list we'd defined previously to add the includes to the IDE, and installs those headers.
Best wishes,
Alex
=> Fix #263 - Install only the headers which are enabled.

CHANGES.md, include/tins/tins.h
I build the library with LIBTINS_ENABLE_DOT11=0. The installation procedure removes tins/dot11.h and tins/dot11/*.h from list of headers to install. Therefore, tins.h must not try to include dot11.h in this configuration of the library.
=> Don't include dot11.h in tins.h if it is not configured in the library

CHANGES.md, include/tins/pdu_iterator.h
Use operator->() instead.
ubsan reports:
src/pdu_iterator.cpp:55:13: runtime error: reference binding to null pointer of type 'const struct PDU'
#0 0x55c6ca in Tins::PDUIterator::operator*() const src/pdu_iterator.cpp:55
#1 0x4e33f2 in bool Tins::operator==<Tins::PDUIterator>(Tins::PDUIteratorBase<Tins::PDUIterator> const&, Tins::PDUIteratorBase<Tins::PDUIterator> const&) (tests/pdu_iterator_test+0x4e33f2)
#2 0x4e0aa2 in bool Tins::operator!=<Tins::PDUIterator>(Tins::PDUIteratorBase<Tins::PDUIterator> const&, Tins::PDUIteratorBase<Tins::PDUIterator> const&) (tests/pdu_iterator_test+0x4e0aa2)
#3 0x4e3119 in std::iterator_traits<Tins::PDUIterator>::difference_type std::__distance<Tins::PDUIterator>(Tins::PDUIterator, Tins::PDUIterator, std::input_iterator_tag) …
=> ubsan: don't call &* on possibly null iterator

CHANGES.md, src/tcp.cpp, tests/src/tcp_test.cpp
It is invalid for options (other than EOL) to occur after EOL. However,
most network stacks will stop processing options at EOL, meaning that
any further options will be ignored, including if they make the options
field malformed. We should likewise stop processing at EOL as otherwise
we will reject packets that most network stacks accept.
Similarly, when writing out options use EOL as end padding, instead of
NOP.
Test.
=> Ignore (possibly malformed) options after EOL

include/tins/exceptions.h, include/tins/ipv6.h, src/ipv6.cpp, tests/src/ipv6_test.cpp
Add classes for IPv6 extension headers defined in the IPv6 protocol
specification (RFC 2460) as well as functions for creating them from
the IPv6 class' ext_header type.
The currently known extension headers are Hop-By-Hop Option,
Destination Routing, Routing and Fragment.
=> Add parsing of well known IPv6 extension headers

src/hw_address.cpp
During my usage of a profiler to optimize a program using libtins to analyze a pcap file and collect statistics, I noticed many temporary allocations for a string stream and traced it to hw_address_to_string.
I rewrote it to use a string instead, which results in only a single allocation per function call. The code isn't very pretty, but it did have a noticeable effect on the performance of my program.
I also removed storage_to_string since hw_address_to_string was its only user.
=> Reduction of memory allocations for hw_address_to_string

include/tins/exceptions.h
I think the access specifier got lost during commit af71a4eca7b9d284ccca879118871c1b3f070cab.
=> Added base class access specifier for socket_close_error

src/ethernetII.cpp, tests/src/dot1q_test.cpp
The recent change to serialize QinQ packets properly broke serialization of single VLAN tagged packets. The serialize code in `EthernetII` was not setting the payload type of Dot1Q packets. This PR is a simple fix for that.
=> Fix Dot1Q serialization for non-qinq packets

include/tins/utils/radiotap_parser.h, src/utils/radiotap_parser.cpp
=> Buffer overflow fixes for radiotap.

include/tins/ip.h, include/tins/pdu.h, src/packet_writer.cpp, src/pdu.cpp
This pull request should fix issue #300.
I implemented a virtual method `PDU::advertised_size()`, which defaults to the sum of `header_size() + trailer_size()` plus `advertised_size()` of all inner PDUs down to the IP PDU.
The `IP::advertised_size()` method returns the `tot_len` instead.
The PacketWriter now uses this virtual method to determine the frame length before writing the packet out.
Please let me know if this solution is to your liking.
=> Fix frame length

cmake/Modules/CheckCXXFeatures.cmake
CMake defines CMAKE_CROSSCOMPILING when crosscompiling so
use that instead of the undefined CROSS_COMPILING variable.
=> Fix check whether we are crosscompiling

CMakeLists.txt
Default cmake configuration path is different for unix subsystems [1].
[1]: https://cmake.org/cmake/help/v3.8/command/find_package.html
=> cmake: update location of cmake configuration files for unix subsystems

examples/portscan.cpp, examples/tcp_connection_close.cpp, include/tins/tcp.h, src/tcp.cpp, src/tcp_ip/flow.cpp, src/tcp_ip/stream.cpp, src/tcp_ip/stream_follower.cpp, src/tcp_stream.cpp
On various places was used simple comparison for checking state of flags.
`tcp.flags() == (TCP::SYN | TCP::ACK)`
This is not what you want usually, because this check is false
in case that another flag is set also. Correct check for syn-ack
packet should be:
`(tcp.flags() & (TCP::SYN | TCP::ACK)) == (TCP::SYN | TCP::ACK)`
To simplify this kind of check, add new has_flags method:
`bool TCP::has_flags(small_uint<12> check_flags) const`
=> simplify tcp flag checks, fix stream_follower

src/tcp_ip/stream_follower.cpp
If not attaching to existing flows, a new TCP flow starts by the first packet from the client, which has SYN without ACK, and not by the reply packet from the server, which has SYN+ACK.
=> Fix detection of a new TCP flow

src/offline_packet_filter.cpp, src/packet_writer.cpp
This series fixes two issues.
1. Using pcap_geterr after handle_ is closed.
2. Failing to free filter_ and handle_ on construction error.
Found by Valgrind.
=> Fix several leaks

include/tins/ipv6_address.h, src/ipv6_address.cpp
Hi. In our project, it is useful to check if some IPv6 address is link-local. What about to add this check to libtins directly?
=> add IPv6 check for Link-Local unicast address

include/tins/icmpv6.h, include/tins/ip.h, include/tins/llc.h
The MS C++ compiler doesn't seem to understand that a small constant
like 0, although strictly being an integer, will fit perfectly fine
into an 8 bit type so add some safe casts to silence that warning.
=> Fix compiler warnings from MSVC 2017

include/tins/tins.h
If libpcap support has been disabled (LIBTINS_ENABLE_PCAP=OFF)
then the headers requiring that library will not be installed,
but they will still be included from the main tins.h convenience
header.
This fixes that by sorrounding the includes with an #ifdef the
same way it has been done for DOT11 support.
=> Don't include non-existing headers when installed without libpcap

src/utils/routing_utils.cpp
Fix `query_route_table()` returning a buffer padded with extra '\0' bytes because it ignored the buffer size returned by `sysctl()`.
This caused `route_entries()` / `route6_entries()` to fall into an infinite loop, forever trying to parse a 0-length routing entry.
=> Fix infinite loop when querying BSD routing table

include/tins/icmp.h, src/icmp.cpp
Host endian has been implicitly converted to big endian in "IPv4Address::operator uint32_t()"
=> Fix wrong address endian

include/tins/dns.h
While reading the DNS class reference in the documentation I noticed that the getter methods were labeled as setters in the description field, so I fixed the comments in the header file to solve that.
=> Fix getter being labeled as setter in dns header file comments

include/tins/exceptions.h, src/dns.cpp
=> Fix DNS decompression bug and add descriptive exceptions 

include/tins/packet_sender.h, src/ipv6.cpp
Attempting to send a `Tins::IPv6` PDU with a link-scope destination address will result in a "Network is unreachable" error (error code 101).
From the RFC2553 document section 3.3, it states
> The sin6_scope_id field is a 32-bit integer that identifies a set of interfaces
> as appropriate for the scope of the address carried in the sin6_addr field. 
> For a link scope sin6_addr, sin6_scope_id would be an interface index.
It understand this might be argued against since we're allowing a non-link layer PDU to be sent through a specified interface, but overall I think this should be up to the user to decide if a packet should be sent through a specified interface or allow the kernel to do so. Maybe that will be another pull request.
=> IPv6 use interface when sending to link-local dest

src/ipv6.cpp
Fix conflict between variable and macro name when building on Msys2 / MinGW64.  
The errors that occurred are:  
```
libtins/src/ipv6.cpp:377:35: error: expected primary-expression before 'struct'
377 |         link_addr.sin6_scope_id = interface.id();
|                                   ^~~~~~~~~
ninja: build stopped: subcommand failed.
```
This change defines WIN32_LEAN_AND_MEAN and prevents interface macros from being defined.
=> Fix conflict between variable and macro name

CMakeLists.txt
On some platforms (like RedHat ones), CMAKE_INSTALL_LIBDIR is set to `lib64` instead of `lib`. The CMake files should also be installed to `lib64`, but because CONF_CMAKE_INSTALL_DIR is set unconditionally to use `lib`, the proper path can't be configured.
This change makes CONF_CMAKE_INSTALL_DIR use the configured CMAKE_INSTALL_LIBDIR value, which defaults to `lib`.
An alternative to this change would be to allow CONF_CMAKE_INSTALL_DIR to be specified manually rather than unconditionally setting it.
=> Use CMAKE_INSTALL_LIBDIR in CONF_CMAKE_INSTALL_DIR

src/ip_address.cpp, tests/src/address_range_test.cpp
According to the C/C++ Standard, for shift operations, the behavior is undefined if the right operand is equal to the width of the promoted left operand.
On a 64-bit Windows machine, this causes IP addresses 0.0.0.0 and 255.255.255.255 to have the same internal representation, leading to various issues when using a /0 prefix.
=> fix incorrect IP address range calculation when using /0 prefix (#484)

include/tins/ip_address.h
Due to changes in GCC13 need fix include.
https://gcc.gnu.org/gcc-13/porting_to.html#header-dep-changes
Else this error happen
```
/builddir/build/BUILD/libtins-4.4/src/../include/tins/ip_address.h:265:31: error: 'uint32_t' is not a member of 'std'; did you mean 'wint_t'?
265 |         return std::hash<std::uint32_t>()(addr);
|                               ^~~~~~~~
```
=> Fix build with GCC13

include/tins/icmpv6.h
`<algorithm>` is needed for std::fill (error in clang-16)
=> Add missing include

src/ipv6.cpp
IPv6 data packets with payload or padded bytes received after one with no Next Header were not being parsed correctly, resulting in NULL PDU.
This commit fixes the IPv6 parser to be compliant with RFC 2460 Section 4.7 by adding a check in the IPv6 constructor to ignore the subsequent packets if an IPv6 packet contains no Next Header.
Signed-off-by: James Raphael Tiovalen <jamestiotio@gmail.com>
=> Ignore IPv6 packets with payload after one with no Next Header

include/tins/sniffer.h, src/sniffer.cpp
This PR adds two overloads for the `FileSniffer` class:
```c++
FileSniffer(FILE *fp, const SnifferConfiguration& configuration);
FileSniffer(FILE *fp, const std::string& filter = "");
```
The possibility of opening a pcap by providing a FILE pointer adds more flexibility, e.g. for working with pipes.
=> Add FileSniffer constructor with FILE pointer as pcap source

include/tins/rawpdu.h, src/tcp_ip/data_tracker.cpp, src/tcp_ip/flow.cpp
unqualified call to 'std::move' [-Wunqualified-std-cast-call]
=> Qualify calls to std::move (clang 15)

include/tins/pdu.h, include/tins/tins.h, include/tins/vxlan.h, src/CMakeLists.txt, src/vxlan.cpp, tests/src/CMakeLists.txt, tests/src/vxlan_test.cpp
This patch adds a new PDU class to support VXLAN. Several VXLAN-related tests have also been added.
This PR closes #16.
Signed-off-by: James Raphael Tiovalen <jamestiotio@gmail.com>
=> Add VXLAN support

src/CMakeLists.txt
With this change, running `make install` should now install the `vxlan.h` header file.
Thanks to @paulie-g for mentioning about this [here](https://github.com/mfontanini/libtins/commit/850bb9b642a2f842808c53e83b275204777cae7f#commitcomment-115766657). It seems that I forgot to add the header file. 😅
=> Add vxlan.h to CMakeLists.txt

src/network_interface.cpp, src/utils/routing_utils.cpp
Update to allow calls to `getifaddrs()` and `freeifaddrs` on Android systems with API Level 24+
Support in Android: https://android.googlesource.com/platform/bionic/+/master/libc/include/ifaddrs.h
=> Resolves #525 Android 24+ support

tests/src/vxlan_test.cpp
Based on RFC 7348, the default IANA-assigned destination UDP port number for VXLAN is 4789, not the source port number. Update the value in the VXLANTest class to align with the RFC.
The VXLAN implementation still allows for the destination port number to be configurable to allow interoperability (as specified by the RFC), such as with the Linux kernel's default value of 8472.
=> Update VXLANTest destination port number

src/crypto.cpp, src/tcp_ip/stream.cpp
This commit replaces the remaining `rfind_pdu` calls to `find_pdu` in the `src` directory. Any existing `rfind_pdu` calls in the `examples` and `tests` directories are unmodified.
The main motivation is that conditional statements are generally more performant than exception handling. Since `rfind_pdu` calls `find_pdu` internally anyway, this eliminates some overhead as well.
=> Replace remaining `rfind_pdu` calls to `find_pdu` in `src` directory
